-   repo: https://github.com/pre-commit/mirrors-isort
    rev: master
    hooks:
    -   id: isort
        args: []
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: master
    hooks:
    -   id: requirements-txt-fixer
-   repo: https://github.com/myint/autoflake
    rev: master
    hooks:
    -   id: autoflake
        args:
          - --in-place
          - --remove-unused-variables
          - --remove-all-unused-imports
          - --expand-star-imports
          - -r
          - main
          - videoanalyst
          - demo
-   repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.28.0
    hooks:
    -   id: yapf
        args: [-p, -r, -i, --style=.style.yapf, main, videoanalyst, demo]
